<?php

namespace AppBundle\Repository;

/**
 * Img_webRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Img_webRepository extends \Doctrine\ORM\EntityRepository
{
}
