<?php

namespace AppBundle\Repository;

/**
 * ommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
