<?php

namespace AppBundle\Repository;

/**
 * Output_webRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Output_webRepository extends \Doctrine\ORM\EntityRepository
{
}
