<?php

namespace AppBundle\Repository;

/**
 * UsrRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsrRepository extends \Doctrine\ORM\EntityRepository
{
}
